main/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('^$', views.home, name="home"),
    url('^create user$', views.create_user, name="create-user"),
    url('^logout$', views.signout, name="logout"),
    url('^get-projects/$', views.load_projects, name="load-projects"),
    url('^get-projects/(?P<content>[a-z-A-Z-0-9]+)$', views.load_projects_with_filter, name="load-projects-with-filter"),
    url('^search/$', views.search, name="search"),
    url('^search/user/(?P<content>[a-z-A-Z-0-9]+)$', views.search_user, name="search-user"),
    url('^search/project/(?P<content>[a-z-A-Z-0-9]+)$', views.search_project, name="search-project"),
    url('^get-user/(?P<content>[a-z-A-Z-0-9]+)$', views.load_user, name='load-user'),
    url('^Dashboard/$', views.dashboard, name="dashboard"),
    url('^friends/send-request$', views.send_friend_request, name="send-friend-request"),
    url('^sync$', views.sync, name="sync"),
    url('^friends/accept-request$', views.accept_request, name="accept-request"),
    url('^friends/decline-request$', views.decline_request, name="decline-request"),
    url('^friends/view$', views.ViewFriends.as_view(), name="view-friends"),
    url('^friends/remove$', views.unfriend, name="remove-friend"),
    url('^Dashboard/create-project$', views.create_project, name="create-project"),
    url('^profile/$', views.EditProfile.as_view(), name="edit-profile"),
    url('^remove-invitation$', views.remove_invitation, name="remove-invitation"),
    url('^rate$', views.rate_project, name='rate'),
    url('^load-friends$', views.load_friends, name='load-friends'),
    url('^invite-friend$', views.invite_friend, name='invite-friend'),
    url('^profile/change-password$', views.ChangePassword.as_view(), name="change-password"),
    url('^project/view/(?P<pk>[0-9]+)$', views.ViewProject.as_view(), name="view-project"),
    url('^project/edit/(?P<pk>[0-9]+)$', views.EditProject.as_view(), name="edit-project"),
    url('^project/delete$', views.delete_project, name="delete-project"),
    url('^leave-comment$', views.leave_comment, name="leave-comment")


]

weShare/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('static_pages.urls', namespace="static-pages")),
    url(r'^home/', include('main.urls', namespace="main"))
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Project(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    description = models.TextField(max_length=500)
    total_rating = models.IntegerField(default=0, null=True)

    title = models.CharField(max_length=20)
    rating = models.IntegerField(default=0, null=True, blank=True)
    address = models.CharField(max_length=25)
    pub_date = models.DateField(auto_now_add=True)

    longitude = models.FloatField()
    latitude = models.FloatField()
    rated_users = models.IntegerField(default=0, null=True)
    image = models.ImageField(upload_to="project_images", null=False, blank=False)

    def __str__(self):
        return self.user.username + '-' + self.name + '-' + str(self.pk)

    def get_absolute_url(self):
        return reverse("main:view-project", kwargs={'pk': self.pk})


class Suggestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ' --> ' + self.project.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_type = models.CharField(blank=False, max_length=10)

    suggestions = models.ManyToManyField(Suggestion, blank=True)
    rated_projects = models.ManyToManyField(Project, blank=True)
    image = models.ImageField(default='/user_images/default_image.png', upload_to='user_images', blank=True, null=True)

    def __str__(self):
        return self.user.username


class Friends(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    array = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.user.username


class PendingFriendRequests(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    array = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.project.user.username + '-' + self.project.name

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, get_object_or_404
from django.utils.decorators import method_decorator
import urllib
import urllib2
import json
from django.http import Http404
from .models import *
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from .forms import *
from django.views.generic import DetailView, ListView
from django.views.generic.edit import UpdateView
from django.conf import settings
import math

index = 0
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November',
          'December']

user_card_info = """
        <div class="card h-100">
            <a href="#"><img class="card-img-top" width="700" height="350" src="%s" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">%s</a>
              </h4>
                 <p class="card-text">name: %s %s</p>
                 <p>email: %s</p>
                 """

user_card_friends = """<div style="text-align: right"><p style="color: #132">already friends</p></div>"""

user_card_request_sent = """<div style="text-align: right"><p style="color: #132">sent a request</p></div>"""

user_card_request_not_sent = """<div style="text-align: right"><a id="%s" class="btn btn-primary" onclick="sendFriendRequest(this)" href="#">send friend request</a></div>"""

project_card = """<div class="card h-100">
              <div class="card-header" style="height: 80px">
                <div class="row">
                   <img src="%s" alt="img" width="50" height="50"/>
                    <p class="card-header-name">%s</p>
                    <p class="card-date">%s</p>
                </div>
              </div>
            <a href="%s"><img class="card-img-top" width="700" height="300" src="%s" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                  <a href="%s" style="margin-right: 5px">%s</a><span class="card-date" style="margin: 0;font-size: 13px">--%s</span>
              </h4>
              <p class="card-text">%s</p>
            </div>
          </div>
          """

friend_request = """<div>
                          <p> <b>%s</b> wants to be a friend with you</p>
                          <a id="accept-%s" onclick="acceptRequest(this)" style="width: 60px;padding: 3px" href="#" class="btn btn-success">accept</a>
                          <a id="decline-%s" onclick="declineRequest(this)" href="#">decline</a>
                          <div class="dropdown-divider"></div>
                      </div>
                      """

friend_suggestion = """<p><b>%s</b> invites you to see <a onclick="removeInvitation(this)" id="%s" href="%s">%s</a></p>"""

comment_formation  ="""<p>%s</p>
                  <small class="text-muted">Posted by %s on %s</small>
                  <hr/>"""

def aproximate(number):
    if int(number)+.5 <= number:
        return int(math.ceil(number))
    return int(math.floor(number))


def load_projects(request):
    global index
    index += 1
    projects = Project.objects.order_by('rating')
    if index >= len(projects):
        return JsonResponse({})

    project = projects[index]
    project.description = project.description[:80] + '...'
    return JsonResponse(create_project_data(project))


def load_projects_with_filter(request, content):
    global index
    index += 1
    projects = Project.objects.filter(name__contains=content)
    if index >= len(projects):
        return JsonResponse({})

    project = projects[index]
    project.description = project.description[:80] + '...'
    return JsonResponse(create_project_data(project))


@login_required()
def send_friend_request(request):
    user = get_object_or_404(User, pk=request.GET.get('pk', -1))
    if request.user.profile in user.friends.array.all() or request.user.profile in user.friends.array.all():
        return JsonResponse({})

    user.pendingfriendrequests.array.add(request.user.profile)
    user.pendingfriendrequests.save()
    return JsonResponse({'html': '<p style="color: #132">request sent</p>'})


def create_project_data(project):
    card = project_card%(project.user.profile.image.url, project.user.username,
                         project.pub_date, reverse('main:view-project', kwargs={'pk': project.pk}),
                         project.image.url, reverse('main:view-project', kwargs={'pk': project.pk}),
                         project.name, project.address, project.description)

    return {'html': card}


def create_user_data(user):
    card = user_card_info % (user.profile.image.url, user.username, user.first_name, user.last_name, user.email)
    if user.is_friend:
        card += user_card_friends
    elif user.request_sent:
        card += user_card_request_sent
    else:
        card += user_card_request_not_sent % (user.pk)

    card += "</div></div>"

    return {'html': card}


def load_user(request, content):
    global index
    index += 1

    users = User.objects.filter(username__contains=content, profile__account_type='normal').exclude(username=request.user.username)
    if index >= len(users):
        return JsonResponse({})
    if request.user.profile in users[index].friends.array.all():
        users[index].is_friend = True
    else:
        users[index].is_friend = False

    if request.user.profile in users[index].pendingfriendrequests.array.all() or users[index].profile in request.user.pendingfriendrequests.array.all():
        users[index].request_sent = True
    else:
        users[index].request_sent = False

    return JsonResponse(create_user_data(users[index]))


def signout(request):
    logout(request)
    return redirect(reverse('static-pages:index'))


def create_user(request):
    try:
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
            }
        
        data = urllib.urlencode(values)
        req = urllib2.Request(url, data)
        response = urllib2.urlopen(req)
        result = json.load(response)
        if not result['success']:
           raise ''
  
        user = User()
        user.username = request.POST['username']
        user.email = request.POST['email']

        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']

        user.save()
        Profile(user=user, account_type=request.POST['user-type']).save()
    except:
        return redirect(reverse("static-pages:index"))

    if user.profile.account_type == 'normal':
        Friends(user=user).save()
        PendingFriendRequests(user=user).save()

    login(request, user)
    return redirect(reverse("main:home"))


@login_required()
def home(request):
    global index
    index = 8
    projects = Project.objects.order_by('rating')[:9]

    for project in projects:
        project.description = project.description[:80] + '...'

    normal_account = True if request.user.profile.account_type == 'normal' else False

    context = {
        'user': request.user,
        'custom_bootstrap': True,
        'normal_account': normal_account,
        'home_active': 'active',
        'data_url': reverse('main:load-projects'),
        'projects': projects

    }

    return render(request, 'main/home/home.html', context)


@login_required()
def search(request):
    option = request.POST['search_option']
    content = request.POST['content']

    if content == "":
        return redirect(reverse('main:home'))

    if ' ' in content:
        content = ''.join(content.split(' '))

    if option == 'user':
        return HttpResponseRedirect(reverse('main:search-user', kwargs={'content': content}))

    return HttpResponseRedirect(reverse('main:search-project', kwargs={'content': content}))


@login_required()
def search_user(request, content):
    if request.user.profile.account_type != 'normal':
        raise Http404
    global index
    users = User.objects.filter(username=content, profile__account_type='normal').exclude(username=request.user.username)

    if not users.exists():
        users = User.objects.filter(username__contains=content, profile__account_type='normal').exclude(username=request.user.username)

    if len(users) > 9:
        users = users[:9]
        index = 8
    else:
        index = len(users) - 1

    for user in users:
        if user.profile in request.user.friends.array.all():
            user.is_friend = True
        else:
            user.is_friend = False

        if request.user.profile in user.pendingfriendrequests.array.all() or\
                        user.profile in request.user.pendingfriendrequests.array.all():
            user.request_sent = True
        else:
            user.request_sent = False

    context = {
        'user': request.user,
        'users': users,
        'custom_bootstrap': True,
        'normal_account': True if request.user.profile.account_type == 'normal' else False,
        'data_url': reverse('main:load-user', kwargs={'content': content}),
    }
    if not users.exists():
        context['not_found'] = "couldn't find user " + content

    return render(request, 'main/home/home.html', context)


@login_required()
def search_project(request, content):
    global index
    projects = Project.objects.filter(name=content)
    if not projects.exists():
        projects = Project.objects.filter(name__contains=content)

    if len(projects) > 9:
        index = 8
    elif len(projects) < 9 and len(projects) != 0:
        index = len(projects) - 1

templates/main/footer.html
<footer id="footer" class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; weShare 2018</p>
      </div>
</footer>

templates/main/friends.html
{% extends 'base.html' %}

{% block body %}

    {% include 'main/navbar.html' %}
    <div class="container" style="margin-top: 120px">
        {% if not friends %}
            <h1 style="text-align: center" class="text-muted">you have no current friends</h1>
        {% endif %}
        <ul class="list-group">
            {% for friend in friends %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <b>{{ friend.user.username }}</b>
                    <a class="btn btn-outline-danger" id="{{ friend.id }}" onclick="removeFriend(this)" href="#">unfriend</a>
                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}


{% block javascript %}
    <script>
        function removeFriend(friend) {
            friend.parentElement.disabled = true;
            $.ajax({
               url: "{% url 'main:remove-friend' %}",
               data: {id: parseInt(friend.id)},
               success: function(data) {
                   friend.parentElement.remove();
               }

            });
        }
        {% include 'main/home/sync.js' %}
    </script>

{% endblock %}

templates/main/navbar.html
{% load staticfiles %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <img src="{% static 'weshare.png' %}" alt="weShare" width="40" height="40" style="text-align: left"/>
        <a class="navbar-brand" href="#">weShare</a>

        <form class="form-inline my-2 my-lg-0"  method="post" action="{% url 'main:search' %}"> {% csrf_token %}

            <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search" name="content" style="margin-left: 50px;width: 250px">
            <select name="search_option" class="custom-select custom-select-md">
                <option value="project">project</option>
                {% if normal_account %}
                    <option value="user">user</option>
                {% endif %}
            </select>
        </form>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">welcome<u style="color: #f4ff95"> {{ user.first_name }} {{ user.last_name }}/</u></a>
            </li>
            <li class="nav-item {{ home_active }}">
              <a class="nav-link" href="{% url 'main:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item {{ profile_active }}">
              <a class="nav-link" href="{% url 'main:edit-profile' %}">Profile</a>
            </li>

              {% if normal_account %}
            <li class="nav-item dropdown {{ friends_active }}">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                  {% if user.profile.suggestions.all %}
                      <span class="badge badge-primary badge-pill">{{ user.profile.suggestions.all.count }}</span>
                  {% else %}
                      <span id="invitation-count" class="badge badge-primary badge-pill" hidden></span>
                  {% endif %}
                  Friends
                  {% if user.pendingfriendrequests.array.all %}
                      <span id="pending-friend-request" class="badge badge-success badge-pill">{{ user.pendingfriendrequests.array.all.count }}</span>
                  {% else %}
                      <span id="pending-friend-request" hidden class="badge badge-success badge-pill">0</span>
                  {% endif %}
              </a>
              <div class="dropdown-menu" style="width: 150%;white-space: normal;text-align: center" aria-labelledby="navbarDropdown">
                  <a href="{% url 'main:view-friends' %}" style="text-align: center">view friends</a>
                  <div class="dropdown-divider"></div>
                  <div id="friends-requests">
                  {% for profile in user.pendingfriendrequests.array.all %}
                      <div>
                          <p> <b>{{ profile.user.username }}</b> wants to be a friend with you</p>
                          <a id="accept-{{ profile.pk }}" onclick="acceptRequest(this)" style="width: 60px;padding: 3px" href="#" class="btn btn-success">accept</a>
                          <a id="decline-{{ profile.pk }}" onclick="declineRequest(this)" href="#">decline</a>
                          <div class="dropdown-divider"></div>
                      </div>
                  {% endfor %}
                  {% for invitation in user.profile.suggestions.all %}
                      <div>
                          <p><b>{{ invitation.user }}</b> invites you to see <a onclick="removeInvitation(this)" id="{{ invitation.id }}" href="{% url 'main:view-project' invitation.project.pk %}">{{ invitation.project.name }}</a></p>
                      </div>
                  {% endfor %}
                  </div>
              </div>
            </li>
             {% else %}
                <li class="nav-item {{ dashboard_active }}">
                    <a class="nav-link" href="{% url 'main:dashboard' %}">Dashboard</a>
                </li>
             {% endif %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:logout' %}">logout</a>
            </li>
          </ul>

        </div>
      </div>
</nav>

templates/main/profile.html
{% extends 'base.html' %}

{% block body %}
    <style>

    .main {
        background-color: #eaf8ff;
        box-shadow: 5px 5px 5px 5px #888888;
        width: 600px;
        {% if password_phase %}
        height: 300px;
        {% else %}
        height: 500px;
        {% endif %}
        margin-top: 80px;
        margin-bottom: 20px;

    }


    #form {
        padding: 20px;
    }

    .sub > * {
        width: 300px;
    }

    .row {
        margin-top: 25px;
    }

    </style>
    {% include 'main/navbar.html' %}
    <form class="main container" id="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}

        {% for field in form %}
        <div class="row">
            <div class="col col-md-3">
                <p>{{ field.label_tag }} </p>
            </div>
            <div class="col col-md-6">
                <div class="sub" {% if not password_phase %}style="font-size: 12px"{% endif %}>
                    {{ field.errors}}
                    {{ field }}
                </div>
            </div>
        </div>
        {% endfor %}
        {% if not password_phase %}
            current image: <img src="{{ image }}" width="50" height="50" alt="image"/><br/>
            <a href="{% url 'main:change-password' %}">change password from here.</a>
        {% endif %}

        <button type="submit" class="btn btn-success" style="margin-left: 430px;{% if password_phase %}margin-top:70px;{% endif %}">submit changes</button>
    </form>


    {% include 'main/footer.html' %}
{% endblock %}

templates/main/project_view.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

    <!-- Custom styles for this template -->
    <link href="{% static 'main/home/css/shop-item.css' %}" rel="stylesheet">
    <style>
      #footer {
          margin-top: 10px;
      }

      #map {
          width: 50%;
          height: 100%;
          background-color: grey;
      }

      .user-detail {
          background-color: #FFF;
      }
        .loader {
        border: 16px solid #f3f3f3; /* Light grey */
        border-top: 16px solid #3498db; /* Blue */
        border-radius: 50%;
        width: 100px;
        height: 100px;
        animation: spin 2s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }

    </style>
{% endblock %}

  {% block body %}

    <!-- Navigation -->
    {% include 'main/navbar.html' %}

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">
          <h1 class="my-4">{{ project.name }}</h1>
          <div class="user-detail">
              <p>user: {{ project.user.username }}</p>
              <p>email: {{ project.user.email }}</p>
          </div>
          {% if normal_account %}
          <button class="btn btn-primary btn-lg" onclick="loadFriends()" data-toggle="modal" data-target="#exampleModalLong">invite friend</button>
          {% endif %}
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div class="card mt-4">
              <div class="row">
                  <img id="img"  style="width: 426.5px;height: 331.717px"  src="{{ project.image.url }}"  alt="img"/>
                  <div id="map"></div>
              </div>
            <div class="card-body">
              <h3 class="card-title">{{ project.title }}</h3>
              <h4>{{ project.address }}</h4>
              <p class="card-text">{{ project.description }}</p>
                <span class="text-warning">
                   {% for i in full_stars %}
                        &#9733;
                    {% endfor %}
                    {% for i in empty_stars %}
                        &#9734;
                    {% endfor %}
                </span>
              {{ project.rating }} stars
              {% if not user_rated %}
              <div>
                <input type="number" style="width: 50px;margin-left: 20px" value="0" id="rating" min="0" max="5"/>
                <a href="#" onclick="rateProject()">rate project</a>
              </div>
              {% else %}
                  <p>already rated</p>
              {% endif %}
            </div>
          </div>

          <div class="card card-outline-secondary my-4">
            <div class="card-header">
              Project Reviews
            </div>
            <div class="card-body">
              <div class="row">
                  <input type="text" placeholder="leave a comment..." class="col col-md-9.5 form-control" id="comment"/>
                  <button style="margin-left: 3px" id="comment-submit" class="btn btn-success" onclick="leaveComment()" disabled>Leave a Review</button>
              </div>
               <hr/>
              {% for comment in project.comment_set.all reversed %}
                  <p>{{ comment.text }}</p>
                  <small class="text-muted">Posted by {{ comment.user.username }} on {{ comment.pub_date }}</small>
                  <hr/>
              {% endfor %}
            </div>
          </div>

        </div>
        <!-- /.col-lg-9 -->

      </div>
    <!-- Modal -->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">friends</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="friends-view" style="text-align: center">
                  <div class="loader"></div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    {% include 'main/footer.html' %}

  {% endblock %}

{% block javascript %}

    <script>
      var map;
      var longitude;
      var latitude;
      var marker = null;

      function initMap() {
          map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: {{ project.latitude }}, lng: {{ project.longitude }}},
              zoom: 10
          });

          new google.maps.Marker({map: map, position: {
              lat: {{ project.latitude }},
              lng: {{ project.longitude }}
          } })

      }


      {% if normal_account %}
      {% include 'main/home/sync.js' %}

      function loadFriends() {
          $.ajax({
              url: "{% url 'main:load-friends' %}",
              type: 'get',
              success: function(friends) {
                  $(".loader").hide();
                  $("#friends-view").html(friends);

              }
          });
      }

      function inviteFriend(friend) {
          $("#exampleModalLong").modal("hide");
          $.ajax({
              url: "{% url 'main:invite-friend' %}",
              data: {
                  friendId: friend.id,
                  projectId: {{ project.id }}
              },

              success: function() {
                  alert("invitation sent successfully!");
              }
          })
      }

      {% endif %}

      function leaveComment() {
          $.ajax({
              url: "{% url 'main:leave-comment' %}",
              data: {
                  text: $("#comment").val(),
                  projectId: {{ project.id }}
              },
              success: function(comment) {
                  $(".card-body").append(comment);
              }

          })
      }

      $("#comment").on("input",function () {
          if($("#comment").val().length >= 10) {
              $("#comment-submit").prop("disabled", false);
          }else {
              $("#comment-submit").prop("disabled", true);
          }
      });

      {% if not user_rated %}
          function rateProject() {
              $.ajax({
                  url: "{% url 'main:rate' %}",
                  data: {
                      rating: parseInt($("#rating").val()),
                      id: {{ project.id }}
                  },
                  success: function() {
                      field = $("#rating").parent();
                      field.fadeOut();
                      field.html("thanks for your rating");
                      field.fadeIn();
                  }
              });
          }
      {% endif %}
    </script>

   <script src="https://maps.googleapis.com/maps/api/js?key=<your_key>&callback=initMap" async defer></script>

{% endblock %}