main/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('^$', views.home, name="home"),
    url('^create user$', views.create_user, name="create-user"),
    url('^logout$', views.signout, name="logout"),
    url('^get-projects/$', views.load_projects, name="load-projects"),
    url('^get-projects/(?P<content>[a-z-A-Z-0-9]+)$', views.load_projects_with_filter, name="load-projects-with-filter"),
    url('^search/$', views.search, name="search"),
    url('^search/user/(?P<content>[a-z-A-Z-0-9]+)$', views.search_user, name="search-user"),
    url('^search/project/(?P<content>[a-z-A-Z-0-9]+)$', views.search_project, name="search-project"),
    url('^get-user/(?P<content>[a-z-A-Z-0-9]+)$', views.load_user, name='load-user'),
    url('^Dashboard/$', views.dashboard, name="dashboard"),
    url('^friends/send-request$', views.send_friend_request, name="send-friend-request"),
    url('^sync$', views.sync, name="sync"),
    url('^friends/accept-request$', views.accept_request, name="accept-request"),
    url('^friends/decline-request$', views.decline_request, name="decline-request"),
    url('^friends/view$', views.ViewFriends.as_view(), name="view-friends"),
    url('^friends/remove$', views.unfriend, name="remove-friend"),
    url('^Dashboard/create-project$', views.create_project, name="create-project"),
    url('^profile/$', views.EditProfile.as_view(), name="edit-profile"),
    url('^remove-invitation$', views.remove_invitation, name="remove-invitation"),
    url('^rate$', views.rate_project, name='rate'),
    url('^load-friends$', views.load_friends, name='load-friends'),
    url('^invite-friend$', views.invite_friend, name='invite-friend'),
    url('^profile/change-password$', views.ChangePassword.as_view(), name="change-password"),
    url('^project/view/(?P<pk>[0-9]+)$', views.ViewProject.as_view(), name="view-project"),
    url('^project/edit/(?P<pk>[0-9]+)$', views.EditProject.as_view(), name="edit-project"),
    url('^project/delete$', views.delete_project, name="delete-project"),
    url('^leave-comment$', views.leave_comment, name="leave-comment")


]

weShare/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('static_pages.urls', namespace="static-pages")),
    url(r'^home/', include('main.urls', namespace="main"))
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from .models import Project
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth import login


class ProjectCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        if kwargs.has_key("request"):
            self.request = kwargs.pop("request")
        else:
            self.request = None
        super(ProjectCreationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Project
        fields = ['name', 'description', 'image', 'longitude', 'latitude', 'title', 'address']
        widgets = {
            'description': forms.Textarea(attrs={'minlength': '80', 'style': 'width: 100%'}),
            'longitude': forms.NumberInput(attrs={'id': 'longitude', 'style': 'display:none'}),
            'latitude': forms.NumberInput(attrs={'id': 'latitude', 'style': 'display:none'}),

        }

    def save(self, commit=True):

        if self.request is not None:
            project = Project()
            project.user = self.request.user
        else:
            project = self.project

        project.name = self.cleaned_data['name']

        project.description = self.cleaned_data['description']
        project.image = self.cleaned_data['image']
        project.title = self.cleaned_data['title']

        project.address = self.cleaned_data['address']
        project.longitude = float(self.cleaned_data['longitude'])
        project.latitude = float(self.cleaned_data['latitude'])

        if commit:
            project.save()
        return project


class UserProfileForm(forms.ModelForm):
    image = forms.FileField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'required': True})
        }

    def has_no_value(self, field):
        if len(self.cleaned_data[field]) == 0:
            raise ValidationError("this field cannot be empty")
        return self.cleaned_data[field]

    def clean_email(self):
        return self.has_no_value('email')

    def clean_first_name(self):
        return self.has_no_value('first_name')

    def clean_last_name(self):
        return self.has_no_value('last_name')

    def save(self, commit=True):
        user = self.user
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']

        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if self.cleaned_data['image']:
            user.profile.image = self.cleaned_data['image']

        if commit:
            user.profile.save()
            user.save()

        return user


class PasswordChangeForm(UserCreationForm):


    class Meta:
        model = User

        fields = ['password1', 'password2']
        exclude = ('username', 'email', 'password', 'first_name', 'last_name')

    def save(self, commit=True):
        user = self.request.user
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
            login(self.request, user)
        return user

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, get_object_or_404
from django.utils.decorators import method_decorator
import urllib
import urllib2
import json
from django.http import Http404
from .models import *
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from .forms import *
from django.views.generic import DetailView, ListView
from django.views.generic.edit import UpdateView
from django.conf import settings
import math

index = 0
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November',
          'December']

user_card_info = """
        <div class="card h-100">
            <a href="#"><img class="card-img-top" width="700" height="350" src="%s" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">%s</a>
              </h4>
                 <p class="card-text">name: %s %s</p>
                 <p>email: %s</p>
                 """

user_card_friends = """<div style="text-align: right"><p style="color: #132">already friends</p></div>"""

user_card_request_sent = """<div style="text-align: right"><p style="color: #132">sent a request</p></div>"""

user_card_request_not_sent = """<div style="text-align: right"><a id="%s" class="btn btn-primary" onclick="sendFriendRequest(this)" href="#">send friend request</a></div>"""

project_card = """<div class="card h-100">
              <div class="card-header" style="height: 80px">
                <div class="row">
                   <img src="%s" alt="img" width="50" height="50"/>
                    <p class="card-header-name">%s</p>
                    <p class="card-date">%s</p>
                </div>
              </div>
            <a href="%s"><img class="card-img-top" width="700" height="300" src="%s" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                  <a href="%s" style="margin-right: 5px">%s</a><span class="card-date" style="margin: 0;font-size: 13px">--%s</span>
              </h4>
              <p class="card-text">%s</p>
            </div>
          </div>
          """

friend_request = """<div>
                          <p> <b>%s</b> wants to be a friend with you</p>
                          <a id="accept-%s" onclick="acceptRequest(this)" style="width: 60px;padding: 3px" href="#" class="btn btn-success">accept</a>
                          <a id="decline-%s" onclick="declineRequest(this)" href="#">decline</a>
                          <div class="dropdown-divider"></div>
                      </div>
                      """

friend_suggestion = """<p><b>%s</b> invites you to see <a onclick="removeInvitation(this)" id="%s" href="%s">%s</a></p>"""

comment_formation  ="""<p>%s</p>
                  <small class="text-muted">Posted by %s on %s</small>
                  <hr/>"""

def aproximate(number):
    if int(number)+.5 <= number:
        return int(math.ceil(number))
    return int(math.floor(number))


def load_projects(request):
    global index
    index += 1
    projects = Project.objects.order_by('rating')
    if index >= len(projects):
        return JsonResponse({})

    project = projects[index]
    project.description = project.description[:80] + '...'
    return JsonResponse(create_project_data(project))


def load_projects_with_filter(request, content):
    global index
    index += 1
    projects = Project.objects.filter(name__contains=content)
    if index >= len(projects):
        return JsonResponse({})

    project = projects[index]
    project.description = project.description[:80] + '...'
    return JsonResponse(create_project_data(project))


@login_required()
def send_friend_request(request):
    user = get_object_or_404(User, pk=request.GET.get('pk', -1))
    if request.user.profile in user.friends.array.all() or request.user.profile in user.friends.array.all():
        return JsonResponse({})

    user.pendingfriendrequests.array.add(request.user.profile)
    user.pendingfriendrequests.save()
    return JsonResponse({'html': '<p style="color: #132">request sent</p>'})


def create_project_data(project):
    card = project_card%(project.user.profile.image.url, project.user.username,
                         project.pub_date, reverse('main:view-project', kwargs={'pk': project.pk}),
                         project.image.url, reverse('main:view-project', kwargs={'pk': project.pk}),
                         project.name, project.address, project.description)

    return {'html': card}


def create_user_data(user):
    card = user_card_info % (user.profile.image.url, user.username, user.first_name, user.last_name, user.email)
    if user.is_friend:
        card += user_card_friends
    elif user.request_sent:
        card += user_card_request_sent
    else:
        card += user_card_request_not_sent % (user.pk)

    card += "</div></div>"

    return {'html': card}


def load_user(request, content):
    global index
    index += 1

    users = User.objects.filter(username__contains=content, profile__account_type='normal').exclude(username=request.user.username)
    if index >= len(users):
        return JsonResponse({})
    if request.user.profile in users[index].friends.array.all():
        users[index].is_friend = True
    else:
        users[index].is_friend = False

    if request.user.profile in users[index].pendingfriendrequests.array.all() or users[index].profile in request.user.pendingfriendrequests.array.all():
        users[index].request_sent = True
    else:
        users[index].request_sent = False

    return JsonResponse(create_user_data(users[index]))


def signout(request):
    logout(request)
    return redirect(reverse('static-pages:index'))


def create_user(request):
    try:
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
            }
        
        data = urllib.urlencode(values)
        req = urllib2.Request(url, data)
        response = urllib2.urlopen(req)
        result = json.load(response)
        if not result['success']:
           raise ''
  
        user = User()
        user.username = request.POST['username']
        user.email = request.POST['email']

        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']

        user.save()
        Profile(user=user, account_type=request.POST['user-type']).save()
    except:
        return redirect(reverse("static-pages:index"))

    if user.profile.account_type == 'normal':
        Friends(user=user).save()
        PendingFriendRequests(user=user).save()

    login(request, user)
    return redirect(reverse("main:home"))


@login_required()
def home(request):
    global index
    index = 8
    projects = Project.objects.order_by('rating')[:9]

    for project in projects:
        project.description = project.description[:80] + '...'

    normal_account = True if request.user.profile.account_type == 'normal' else False

    context = {
        'user': request.user,
        'custom_bootstrap': True,
        'normal_account': normal_account,
        'home_active': 'active',
        'data_url': reverse('main:load-projects'),
        'projects': projects

    }

    return render(request, 'main/home/home.html', context)


@login_required()
def search(request):
    option = request.POST['search_option']
    content = request.POST['content']

    if content == "":
        return redirect(reverse('main:home'))

    if ' ' in content:
        content = ''.join(content.split(' '))

    if option == 'user':
        return HttpResponseRedirect(reverse('main:search-user', kwargs={'content': content}))

    return HttpResponseRedirect(reverse('main:search-project', kwargs={'content': content}))


@login_required()
def search_user(request, content):
    if request.user.profile.account_type != 'normal':
        raise Http404
    global index
    users = User.objects.filter(username=content, profile__account_type='normal').exclude(username=request.user.username)

    if not users.exists():
        users = User.objects.filter(username__contains=content, profile__account_type='normal').exclude(username=request.user.username)

    if len(users) > 9:
        users = users[:9]
        index = 8
    else:
        index = len(users) - 1

    for user in users:
        if user.profile in request.user.friends.array.all():
            user.is_friend = True
        else:
            user.is_friend = False

        if request.user.profile in user.pendingfriendrequests.array.all() or\
                        user.profile in request.user.pendingfriendrequests.array.all():
            user.request_sent = True
        else:
            user.request_sent = False

    context = {
        'user': request.user,
        'users': users,
        'custom_bootstrap': True,
        'normal_account': True if request.user.profile.account_type == 'normal' else False,
        'data_url': reverse('main:load-user', kwargs={'content': content}),
    }
    if not users.exists():
        context['not_found'] = "couldn't find user " + content

    return render(request, 'main/home/home.html', context)


@login_required()
def search_project(request, content):
    global index
    projects = Project.objects.filter(name=content)
    if not projects.exists():
        projects = Project.objects.filter(name__contains=content)

    if len(projects) > 9:
        index = 8
    elif len(projects) < 9 and len(projects) != 0:
        index = len(projects) - 1

templates/main/home/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'main/home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'main/home/css/3-col-portfolio.css' %}" rel="stylesheet">


{% endblock %}

{% block body %}

    {% if projects %}
        <style>
      .card-header-name {
          font-family: 'Times New Roman', Times, serif;
          font-size: 20px;
          margin-bottom: 0;
          margin-left: 5px;
      }

      .card-date {
          color: #9c9c9c;
          font-size: 10px;
          margin-left: 180px;
      }
    </style>

    {% endif %}
    <!-- Navigation -->
    {% include 'main/navbar.html' %}

    <!-- Page Content -->
    <div class="container">

      {% if not_found %}
          <h1 class="text-muted" style="text-align: center">{{ not_found }}</h1>
          {% else %}
          <!-- Page Heading -->
          {% if projects %}
          <h1 class="my-4">top projects</h1>
          {% else %}
          <h1 class="my-4">top results</h1>
          {% endif %}

      {% endif %}


      <div id="container" class="row">
        {% for project in projects %}
        <div class="col-lg-4 col-sm-6 portfolio-item">

          <div class="card h-100">
              <div class="card-header" style="height: 80px">
                <div class="row">
                   <img src="{{ project.user.profile.image.url }}" alt="img" width="50" height="50"/>
                    <p class="card-header-name">{{ project.user.username }}</p>
                    <p class="card-date">{{ project.pub_date }}</p>
                </div>
              </div>
            <a href="{% url 'main:view-project' project.pk %}"><img class="card-img-top" width="700" height="300" src="{{ project.image.url }}" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                  <a href="{% url 'main:view-project' project.pk %}" style="margin-right: 5px">{{ project.name }}</a><span class="card-date" style="margin: 0;font-size: 13px">--{{ project.address }}</span>
              </h4>
              <p class="card-text">{{ project.description }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      {% for user in users %}

        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" width="700" height="350" src="{{ user.profile.image.url }}" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">{{ user.username }}</a>
              </h4>
                 <p class="card-text">name: {{ user.first_name }} {{ user.last_name }}</p>
                 <p>email: {{ user.email }}</p>
                {% if user.is_friend %}
                    <div style="text-align: right"><p style="color: #132">already friends</p></div>
                    {% elif user.request_sent %}
                    <div style="text-align: right"><p style="color: #132">sent a request</p></div>
                {% else %}
                <div style="text-align: right"><a id="{{ user.pk }}" onclick="sendFriendRequest(this)" class="btn btn-primary" href="#">send friend request</a></div>
                {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    {% include 'main/footer.html' %}

{% endblock %}

{% block javascript %}

    <script>


       var hasData = true;

       function createCard(data) {
           var card = document.createElement("div");
           card.setAttribute("class", "col-lg-4 col-sm-6 portfolio-item");
           card.innerHTML = data.html;
           return card;

       }

       {% if users %}
       function sendFriendRequest(e) {
           $.ajax({
               url: "{% url 'main:send-friend-request' %}",
               type: "get" ,
               data: {pk:parseInt(e.id)},
               success: function(data) {
                   $("#"+e.id).parent().html(data.html)
               }



           });
       }

       {% endif %}

       {% if normal_account %}
       {% include 'main/home/sync.js' %}
       {% endif %}

       function loadContent() {
           $.ajax({
               url: "{{ data_url }}",
               type: 'get',
               success: function(data) {
                   if($(window).scrollTop() + $(window).height() >= $(document).height() - $(".container").height() - 700 && hasData) {
                       hasData = data.html != undefined;
                       if(!hasData) {
                           return;
                       }
                       card = createCard(data);
                       $("#container").append(card);
                       loadContent();
                   }
               }
           });
       }
       {% if not user_not_found %}
        $(document).ready(function() {
           loadContent();
           $(window).scroll(function() {
              if($(window).scrollTop() + $(window).height() >= $(document).height() - $(".container").height() - 700 && hasData) {
                  loadContent();
               }
           });
       });
       {% endif %}
    </script>

{% endblock %}