main/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('^$', views.home, name="home"),
    url('^create user$', views.create_user, name="create-user"),
    url('^logout$', views.signout, name="logout"),
    url('^get-projects/$', views.load_projects, name="load-projects"),
    url('^get-projects/(?P<content>[a-z-A-Z-0-9]+)$', views.load_projects_with_filter, name="load-projects-with-filter"),
    url('^search/$', views.search, name="search"),
    url('^search/user/(?P<content>[a-z-A-Z-0-9]+)$', views.search_user, name="search-user"),
    url('^search/project/(?P<content>[a-z-A-Z-0-9]+)$', views.search_project, name="search-project"),
    url('^get-user/(?P<content>[a-z-A-Z-0-9]+)$', views.load_user, name='load-user'),
    url('^Dashboard/$', views.dashboard, name="dashboard"),
    url('^friends/send-request$', views.send_friend_request, name="send-friend-request"),
    url('^sync$', views.sync, name="sync"),
    url('^friends/accept-request$', views.accept_request, name="accept-request"),
    url('^friends/decline-request$', views.decline_request, name="decline-request"),
    url('^friends/view$', views.ViewFriends.as_view(), name="view-friends"),
    url('^friends/remove$', views.unfriend, name="remove-friend"),
    url('^Dashboard/create-project$', views.create_project, name="create-project"),
    url('^profile/$', views.EditProfile.as_view(), name="edit-profile"),
    url('^remove-invitation$', views.remove_invitation, name="remove-invitation"),
    url('^rate$', views.rate_project, name='rate'),
    url('^load-friends$', views.load_friends, name='load-friends'),
    url('^invite-friend$', views.invite_friend, name='invite-friend'),
    url('^profile/change-password$', views.ChangePassword.as_view(), name="change-password"),
    url('^project/view/(?P<pk>[0-9]+)$', views.ViewProject.as_view(), name="view-project"),
    url('^project/edit/(?P<pk>[0-9]+)$', views.EditProject.as_view(), name="edit-project"),
    url('^project/delete$', views.delete_project, name="delete-project"),
    url('^leave-comment$', views.leave_comment, name="leave-comment")


]

weShare/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('static_pages.urls', namespace="static-pages")),
    url(r'^home/', include('main.urls', namespace="main"))
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Project(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    description = models.TextField(max_length=500)
    total_rating = models.IntegerField(default=0, null=True)

    title = models.CharField(max_length=20)
    rating = models.IntegerField(default=0, null=True, blank=True)
    address = models.CharField(max_length=25)
    pub_date = models.DateField(auto_now_add=True)

    longitude = models.FloatField()
    latitude = models.FloatField()
    rated_users = models.IntegerField(default=0, null=True)
    image = models.ImageField(upload_to="project_images", null=False, blank=False)

    def __str__(self):
        return self.user.username + '-' + self.name + '-' + str(self.pk)

    def get_absolute_url(self):
        return reverse("main:view-project", kwargs={'pk': self.pk})


class Suggestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ' --> ' + self.project.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_type = models.CharField(blank=False, max_length=10)

    suggestions = models.ManyToManyField(Suggestion, blank=True)
    rated_projects = models.ManyToManyField(Project, blank=True)
    image = models.ImageField(default='/user_images/default_image.png', upload_to='user_images', blank=True, null=True)

    def __str__(self):
        return self.user.username


class Friends(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    array = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.user.username


class PendingFriendRequests(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    array = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.project.user.username + '-' + self.project.name

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, get_object_or_404
from django.utils.decorators import method_decorator
import urllib
import urllib2
import json
from django.http import Http404
from .models import *
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from .forms import *
from django.views.generic import DetailView, ListView
from django.views.generic.edit import UpdateView
from django.conf import settings
import math

index = 0
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November',
          'December']

user_card_info = """
        <div class="card h-100">
            <a href="#"><img class="card-img-top" width="700" height="350" src="%s" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">%s</a>
              </h4>
                 <p class="card-text">name: %s %s</p>
                 <p>email: %s</p>
                 """

user_card_friends = """<div style="text-align: right"><p style="color: #132">already friends</p></div>"""

user_card_request_sent = """<div style="text-align: right"><p style="color: #132">sent a request</p></div>"""

user_card_request_not_sent = """<div style="text-align: right"><a id="%s" class="btn btn-primary" onclick="sendFriendRequest(this)" href="#">send friend request</a></div>"""

project_card = """<div class="card h-100">
              <div class="card-header" style="height: 80px">
                <div class="row">
                   <img src="%s" alt="img" width="50" height="50"/>
                    <p class="card-header-name">%s</p>
                    <p class="card-date">%s</p>
                </div>
              </div>
            <a href="%s"><img class="card-img-top" width="700" height="300" src="%s" alt="img"></a>
            <div class="card-body">
              <h4 class="card-title">
                  <a href="%s" style="margin-right: 5px">%s</a><span class="card-date" style="margin: 0;font-size: 13px">--%s</span>
              </h4>
              <p class="card-text">%s</p>
            </div>
          </div>
          """

friend_request = """<div>
                          <p> <b>%s</b> wants to be a friend with you</p>
                          <a id="accept-%s" onclick="acceptRequest(this)" style="width: 60px;padding: 3px" href="#" class="btn btn-success">accept</a>
                          <a id="decline-%s" onclick="declineRequest(this)" href="#">decline</a>
                          <div class="dropdown-divider"></div>
                      </div>
                      """

friend_suggestion = """<p><b>%s</b> invites you to see <a onclick="removeInvitation(this)" id="%s" href="%s">%s</a></p>"""

comment_formation  ="""<p>%s</p>
                  <small class="text-muted">Posted by %s on %s</small>
                  <hr/>"""

def aproximate(number):
    if int(number)+.5 <= number:
        return int(math.ceil(number))
    return int(math.floor(number))


def load_projects(request):
    global index
    index += 1
    projects = Project.objects.order_by('rating')
    if index >= len(projects):
        return JsonResponse({})

    project = projects[index]
    project.description = project.description[:80] + '...'
    return JsonResponse(create_project_data(project))


def load_projects_with_filter(request, content):
    global index
    index += 1
    projects = Project.objects.filter(name__contains=content)
    if index >= len(projects):
        return JsonResponse({})

    project = projects[index]
    project.description = project.description[:80] + '...'
    return JsonResponse(create_project_data(project))


@login_required()
def send_friend_request(request):
    user = get_object_or_404(User, pk=request.GET.get('pk', -1))
    if request.user.profile in user.friends.array.all() or request.user.profile in user.friends.array.all():
        return JsonResponse({})

    user.pendingfriendrequests.array.add(request.user.profile)
    user.pendingfriendrequests.save()
    return JsonResponse({'html': '<p style="color: #132">request sent</p>'})


def create_project_data(project):
    card = project_card%(project.user.profile.image.url, project.user.username,
                         project.pub_date, reverse('main:view-project', kwargs={'pk': project.pk}),
                         project.image.url, reverse('main:view-project', kwargs={'pk': project.pk}),
                         project.name, project.address, project.description)

    return {'html': card}


def create_user_data(user):
    card = user_card_info % (user.profile.image.url, user.username, user.first_name, user.last_name, user.email)
    if user.is_friend:
        card += user_card_friends
    elif user.request_sent:
        card += user_card_request_sent
    else:
        card += user_card_request_not_sent % (user.pk)

    card += "</div></div>"

    return {'html': card}


def load_user(request, content):
    global index
    index += 1

    users = User.objects.filter(username__contains=content, profile__account_type='normal').exclude(username=request.user.username)
    if index >= len(users):
        return JsonResponse({})
    if request.user.profile in users[index].friends.array.all():
        users[index].is_friend = True
    else:
        users[index].is_friend = False

    if request.user.profile in users[index].pendingfriendrequests.array.all() or users[index].profile in request.user.pendingfriendrequests.array.all():
        users[index].request_sent = True
    else:
        users[index].request_sent = False

    return JsonResponse(create_user_data(users[index]))


def signout(request):
    logout(request)
    return redirect(reverse('static-pages:index'))


def create_user(request):
    try:
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
            }
        
        data = urllib.urlencode(values)
        req = urllib2.Request(url, data)
        response = urllib2.urlopen(req)
        result = json.load(response)
        if not result['success']:
           raise ''
  
        user = User()
        user.username = request.POST['username']
        user.email = request.POST['email']

        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']

        user.save()
        Profile(user=user, account_type=request.POST['user-type']).save()
    except:
        return redirect(reverse("static-pages:index"))

    if user.profile.account_type == 'normal':
        Friends(user=user).save()
        PendingFriendRequests(user=user).save()

    login(request, user)
    return redirect(reverse("main:home"))


@login_required()
def home(request):
    global index
    index = 8
    projects = Project.objects.order_by('rating')[:9]

    for project in projects:
        project.description = project.description[:80] + '...'

    normal_account = True if request.user.profile.account_type == 'normal' else False

    context = {
        'user': request.user,
        'custom_bootstrap': True,
        'normal_account': normal_account,
        'home_active': 'active',
        'data_url': reverse('main:load-projects'),
        'projects': projects

    }

    return render(request, 'main/home/home.html', context)


@login_required()
def search(request):
    option = request.POST['search_option']
    content = request.POST['content']

    if content == "":
        return redirect(reverse('main:home'))

    if ' ' in content:
        content = ''.join(content.split(' '))

    if option == 'user':
        return HttpResponseRedirect(reverse('main:search-user', kwargs={'content': content}))

    return HttpResponseRedirect(reverse('main:search-project', kwargs={'content': content}))


@login_required()
def search_user(request, content):
    if request.user.profile.account_type != 'normal':
        raise Http404
    global index
    users = User.objects.filter(username=content, profile__account_type='normal').exclude(username=request.user.username)

    if not users.exists():
        users = User.objects.filter(username__contains=content, profile__account_type='normal').exclude(username=request.user.username)

    if len(users) > 9:
        users = users[:9]
        index = 8
    else:
        index = len(users) - 1

    for user in users:
        if user.profile in request.user.friends.array.all():
            user.is_friend = True
        else:
            user.is_friend = False

        if request.user.profile in user.pendingfriendrequests.array.all() or\
                        user.profile in request.user.pendingfriendrequests.array.all():
            user.request_sent = True
        else:
            user.request_sent = False

    context = {
        'user': request.user,
        'users': users,
        'custom_bootstrap': True,
        'normal_account': True if request.user.profile.account_type == 'normal' else False,
        'data_url': reverse('main:load-user', kwargs={'content': content}),
    }
    if not users.exists():
        context['not_found'] = "couldn't find user " + content

    return render(request, 'main/home/home.html', context)


@login_required()
def search_project(request, content):
    global index
    projects = Project.objects.filter(name=content)
    if not projects.exists():
        projects = Project.objects.filter(name__contains=content)

    if len(projects) > 9:
        index = 8
    elif len(projects) < 9 and len(projects) != 0:
        index = len(projects) - 1

templates/main/dashboard/dashboard.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'main/home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'main/home/css/dashboard.css' %}" rel="stylesheet">

{% endblock %}

{% block body %}

    <style>
      .alert {
          margin-top: 60px;
          margin-left: 100px;
          margin-right: 100px;
          display: none;
      }

    </style>

    <!-- Navigation -->
    {% include 'main/navbar.html' %}

    <!-- Page Content -->
    <div class="container">

      <div class="alert alert-success alert-dismissible fade show fixed-top" role="alert">
            <strong>project deleted successfully.</strong>
          <button id="close-modal" type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <!-- Page Heading -->
      <h1 class="my-4">your projects</h1>

      <div class="row">
        <div class="col-md-7">
          <a href="{% url 'main:create-project' %}">
            <img class="img-fluid rounded mb-3 mb-md-0" width="635" height="272.133" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>project name</h3>
          <p>Project description provide the following details to the applicants: the problem the project will address, a set of goals for the project, the overall objectives for the project, as well as a project plan that describes the activities the members will undertake.  The project description also includes the location of the project, the length of the project, and any benefits you will receive while serving on the project.</p>
            <a href="{% url 'main:create-project' %}" class="btn btn-outline-primary">share a project now!</a>

        </div>
      </div>
      <hr>
      {% for project in projects %}
      <div id="board{{ project.pk }}" class="row">
        <div class="col-md-7">
          <a href="{% url 'main:view-project' project.pk %}">
            <img class="img-fluid rounded mb-3 mb-md-0" width="635" height="272.133" src="{{ project.image.url }}" alt="">
          </a>
        </div>
        <div class="col-md-5" style="word-wrap: break-word;">
          <h3>{{ project.name }}</h3>
          <p>{{ project.description }}</p>
            <a href="{% url 'main:view-project' project.pk %}" class="btn btn-outline-primary">view project</a>
            <a href="{% url 'main:edit-project' project.pk %}" class="btn btn-outline-success">edit project</a>
            <a href="#" class="btn btn-outline-danger" onclick="confirmDeletion(this)" data-toggle="modal" data-target="#confirm-modal" id="{{ project.pk }}">delete project</a>

        </div>
      </div>
      <!-- /.row -->
      <hr>
     {% endfor %}

    </div>

            <!-- Modal -->
    <div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">delete project</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">are you sure you want to delete this project ?
                </div>
                <div class="modal-footer">
                    <button id="close-modal" type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
                    <button type="button" class="btn btn-danger" onclick="deleteProject()">delete</button>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    {% include 'main/footer.html' %}



{% endblock %}

{% block javascript %}

    <script>

       var projectToDelete;


       function confirmDeletion(e) {
           projectToDelete = e;
       }

       function deleteProject() {
           $("#confirm-modal").modal("hide");

           $.ajax({
              url: "{% url 'main:delete-project' %}",
              type: "get",
              data: {pk: projectToDelete.id} ,
              success: function(data) {
                  $("#board"+data.id).remove();

                  $(".alert").fadeIn();
                  setTimeout(function() {
                      $(".alert").fadeOut();
                  }, 5000);
              }

           });
       }
    </script>
{% endblock %}

templates/main/dashboard/project_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'main/home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'main/home/css/shop-item.css' %}" rel="stylesheet">
    <style>
      #footer {
          margin-top: 10px;
      }


      #map {
          width: 350px;
          height: 300px;
          background-color: grey;
          margin-left: -75px;
      {% if not update_mode %}
          border: 1px solid red;
      {% endif %}

      }

      .help-text {
          color: grey;
          margin-bottom: -3px;
          font-size: 14px
      }

      {% if not update_mode %}
      #id_image {
          display: none;
      }
      {% endif %}

    </style>
{% endblock %}

  {% block body %}

    <!-- Navigation -->
    {% include 'main/navbar.html' %}

    <!-- Page Content -->
    <div class="container">

      <form class="row" method="post" id="form" enctype="multipart/form-data"> {% csrf_token %}

        <div class="col-lg-3" style="margin-top: 15px">
            <p class="help-text">*enter your project name</p>
            {{ form.name }}
            {{ form.longitude }}
            {{ form.latitude }}
            <button type="submit" id="submit-btn" style="margin: 10px 10px 10px 10px" class="btn btn-success btn-lg">submit project</button>
            <p class="help-text">*add marker on the project location</p>
            <div id="map"></div>
        </div>

        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <p id="image-help" class="help-text" style="margin-top: 10px;color: red">*upload image</p>
          <div class="card mt-4">
              {{ form.image }}
              <a href="#" onclick="uploadImage()" ><img class="card-img-top img-fluid" src="{% static 'main/imagePlaceHolder.jpg' %}" style="height: 400px;{% if not update_mode %}border: 1px solid red{% endif %}" alt=""></a>
            <div class="card-body">
              <p class="card-title help-text">*enter a title</p>
              {{ form.title }}

                <p class="card-title help-text">*enter the project address</p>
               {{ form.address }}

              <p class="help-text">*enter a description</p>
              {{ form.description }}

            </div>
          </div>

        </div>

      </form>

    </div>

    <!-- Footer -->
    {% include 'main/footer.html' %}

  {% endblock %}

{% block javascript %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'main/home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'main/home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script>
      var map;
      var longitude = null;
      var latitude = null;
      var marker = null;

      function initMap() {

          {% if update_mode %}
              var position = {lat: {{ latitude }}, lng: {{ longitude }} };
          {% else %}
              var position = {lat: 1.7597445, lng: 15.7024725};
          {% endif %}

          map = new google.maps.Map(document.getElementById('map'), {
              center: position,
              zoom: {% if update_mode %}10{% else %}2{% endif %}
          });

          map.addListener('click', function(event) {
              if(marker != null) {
                  marker.setMap(null);
              }
              marker = new google.maps.Marker({map:map, position: event.latLng});
              latitude = event.latLng.lat();
              longitude = event.latLng.lng();
              $("#latitude").val(latitude);
              $("#longitude").val(longitude);
              $("#map").css("border-color", "green");
        });

          {% if update_mode %}

              marker = new google.maps.Marker({
                  map: map,
                  position: {lat: {{ latitude }}, lng: {{ longitude }} }
              });
          {% endif %}
      }

      function uploadImage() {
          $("#id_image").click();

      }

      $("#id_image").change(function(){
         var imageHelp = $("#image-help");
         imageHelp.text("image uploaded: "+$(this).val());
         imageHelp.css("color", "green");
         $("img").css("border-color", "green");

      });

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<your_key>&callback=initMap" async defer></script>


{% endblock %}